title: Kris's Blog
author: Kristian Georgiev
email: krisgrg@mit.edu
description: Nobody exists on purpose. Nobody belongs anywhere. We’re all going to die. Come watch TV.
github_username:  kristian-georgiev
# Build settings
markdown: kramdown
theme: minima
